service: wunderkind

image: dobrinov/wunderkind

servers:
  web:
    - wunderkind.bg

proxy:
  ssl: true
  host: wunderkind.bg

registry:
  username: dobrinov
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: wunderkind-db
    POSTGRES_DB: wunderkind_production
    POSTGRES_USER: postgres
    DB_PORT: 5432

  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "wunderkind_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64

accessories:
  db:
    image: postgres:17
    host: wunderkind.bg
    port: 127.0.0.1:5432:5432
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: wunderkind_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/structure.sql:/docker-entrypoint-initdb.d/setup.sql
