#!/usr/bin/env ruby
# Builds the ladder corpus: problem files into db/seeds/ladders/, figure SVGs
# into tmp/authoring/svg/ plus a manifest for the rasterizer.
#
#   ruby tools/authoring/build.rb                 # everything
#   ruby tools/authoring/build.rb percent         # only families whose name
#                                                 # starts with "percent"
#
# Then:
#   tools/authoring/rasterize.sh                  # SVG -> PNG
#   bin/rails problems:import FILE=db/seeds/ladders
#
# This runs outside Rails on purpose. Question content is authored outside the
# app — the app has no generator in it and never makes a question at runtime.
require "fileutils"

ROOT = File.expand_path("../..", __dir__)
Dir.chdir(ROOT)
$LOAD_PATH.unshift File.join(ROOT, "tools/authoring/lib")

require "authoring"
require_relative "families/shared"
Dir[File.join(ROOT, "tools/authoring/families/*.rb")].sort.each do |path|
  require path unless path.end_with?("shared.rb")
end

only = ARGV.first

# Texts already in the question bank, dumped by
#   bin/rails runner 'File.write("tmp/authoring/existing.txt", Question.pluck(:body_text).join("\n"))'
# Optional: without it the build still runs, it just cannot see clashes.
existing_path = File.join(ROOT, "tmp/authoring/existing.txt")
taken = File.exist?(existing_path) ? File.readlines(existing_path, chomp: true) : []

rows, report = Authoring.generate(only: only, taken: taken)

HEADER = lambda do |area, problems|
  topics = problems.group_by { |row| row["topic"] }.transform_values(&:size).sort_by { |_, count| -count }
  elos = problems.map { |row| row["elo"] }
  <<~HEAD
    # Ladder corpus: #{area}. Generated by tools/authoring — do not hand-edit,
    # edit the family and rebuild (ruby tools/authoring/build.rb).
    #
    # #{problems.size} problems, Elo #{elos.min}-#{elos.max}, over
    # #{topics.map { |topic, count| "#{topic} (#{count})" }.join(', ')}.
    #
    # Every problem carries the *family* it came from — one type of problem
    # written at six
    # rising difficulties, a handful of variants each (the importer ignores the
    # key). That is what makes the
    # bank teachable: a student who cannot do the type at 1300 meets the same
    # type at 900, and climbs back up as their rating recovers. The rungs are
    # deliberately close together, and the wording of a family stays the same
    # so the student recognises the problem, not just the numbers.
    #
    # Provenance: written for this app. The Bulgarian curriculum sequence
    # (Khan Academy BG's grade tracks) and IXL's skill lists were read for
    # coverage and difficulty order only — no problem text comes from either.
    #
    # Load with:
    #   bin/rails problems:import FILE=db/seeds/ladders/#{area}.yml
  HEAD
end

figures = Authoring.write(rows,
                          out_dir: File.join(ROOT, "db/seeds/ladders"),
                          svg_dir: File.join(ROOT, "tmp/authoring/svg"),
                          manifest: File.join(ROOT, "tmp/authoring/manifest.tsv"),
                          header: HEADER)

puts "Families: #{report[:families]}"
puts "Problems: #{report[:problems]} (#{figures} with a figure)"
puts "Duplicate texts skipped: #{report[:collisions]} (#{report[:bank_clashes].size} clashed with the existing bank)"
report[:bank_clashes].uniq.first(15).each { |text| puts "  bank: #{text}" }
rows.sort_by { |area, _| area }.each { |area, problems| puts format("  %-16s %5d", area, problems.size) }
unless report[:short].empty?
  puts "\nRungs that ran out of distinct variants (#{report[:short].size}):"
  # Empty rungs first: a rung with nothing in it puts a hole in a ladder, which
  # is worse than a rung with fewer variants than asked for.
  empty, thin = report[:short].partition { |line| line.match?(%r{: 0/}) }
  empty.each { |line| puts "  EMPTY #{line}" }
  thin.first(25).each { |line| puts "  #{line}" }
end
