require "rails_helper"

# The ladder corpus (db/seeds/ladders) is the bulk of the shipped question bank:
# ~10.7k problems, generated by tools/authoring from families that write the
# same type of problem at six rising difficulties.
#
# Importing all of it here would cost half a minute, so the structure is checked
# against the files and only a spread-out sample goes through the importer and
# the grader. tools/authoring/check.rb is the fuller check, run at authoring time.
describe "the ladder corpus" do
  let(:topics_file) { Rails.root.join(ProblemSeeds::TOPICS_FILE) }
  let(:files) { Dir[Rails.root.join("db/seeds/ladders/*.yml")].sort }
  let(:problems) { files.flat_map { |path| YAML.safe_load_file(path).fetch("problems") } }
  let(:leaf_topics) { Topic.where.not(parent_id: nil) }

  it "ships as several files, one per area" do
    files.size.should be >= 8
    problems.size.should be >= 10_000
  end

  it "names only topics that exist, and covers every leaf" do
    known = YAML.safe_load_file(topics_file).fetch("topics").values.flatten
    used = problems.map { |problem| problem["topic"] }.uniq

    (used - known).should eq([])
    (known - used).should eq([])
  end

  # The point of the corpus: a student who cannot do a type of problem should
  # meet the same type lower down. Every family is a ladder, so every family has
  # to span several ratings, spaced closely enough to walk down and back up.
  it "gives every family a ladder of ratings" do
    families = problems.group_by { |problem| problem["family"] }
    families.keys.compact.size.should eq(families.size)
    families.size.should be >= 250

    families.each do |name, group|
      elos = group.map { |problem| problem["elo"] }.uniq.sort
      elos.size.should be >= 4, "#{name} has only #{elos.size} rungs"
      (elos.last - elos.first).should be >= 300, "#{name} spans only #{elos.last - elos.first} points"
      elos.each_cons(2) do |low, high|
        (high - low).should be <= 150, "#{name} jumps #{high - low} points between rungs"
      end
    end
  end

  it "spans the whole rating range the dispatcher searches" do
    elos = problems.map { |problem| problem["elo"] }
    elos.min.should be <= 700
    elos.max.should be >= 2000
    (900..1900).step(100).each do |band|
      elos.count { |elo| (band...(band + 100)).cover?(elo) }.should be >= 100, "thin band at #{band}"
    end
  end

  it "explains every problem in steps" do
    problems.each do |problem|
      problem["explanation"].to_s.length.should be >= 120, problem["text"]
      problem["explanation"].should include("\n1) "), problem["text"]
    end
  end

  it "keeps answers in a form the grader can parse" do
    typed = problems.reject { |problem| problem["options"] || problem["widget"] }

    typed.each do |problem|
      ExactValue.parse(problem["answer"]).should_not be_nil, "#{problem['text']} -> #{problem['answer']}"
    end
  end

  it "offers the right answer among the options of every multiple-choice problem" do
    problems.select { |problem| problem["options"] }.each do |problem|
      problem["options"].map(&:to_s).should include(problem["answer"].to_s), problem["text"]
      problem["options"].uniq.size.should eq(problem["options"].size), problem["text"]
    end
  end

  it "points every figure at a PNG that exists" do
    with_images = problems.select { |problem| problem["image"] }
    with_images.size.should be >= 500

    with_images.each do |problem|
      Rails.root.join(problem["image"]).should exist
      problem["image_filename"].should be_present
    end
  end

  it "uses only widgets the app can render and grade, and uses all of them" do
    widgets = problems.filter_map { |problem| problem["widget"] }
    widgets.size.should be >= 10_000

    widgets.each do |widget|
      Widgets.keys.should include(widget["widget"])
      widget["solution"].should be_present
    end

    # Every widget in the registry earns its place: one with no problems behind
    # it is dead code in the answer flow.
    widgets.map { |widget| widget["widget"] }.uniq.sort.should eq(Widgets.keys.sort)
  end

  # A rating band with nothing interactive in it means a student in that band
  # never touches a widget.
  it "spreads the interactive problems from the youngest band to competition level" do
    interactive = problems.select { |problem| problem["widget"] }
    elos = interactive.map { |problem| problem["elo"] }

    elos.min.should be <= 700
    elos.max.should be >= 2500
    [ 600, 900, 1200, 1500, 1800, 2100, 2400 ].each do |band|
      interactive.count { |problem| (band...(band + 300)).cover?(problem["elo"]) }.should be >= 100, "thin band at #{band}"
    end
  end

  # What a student would submit to be right. It is not always the author's
  # solution verbatim: a multi-select solution lists the right ids under
  # "correct" while the widget submits them under "selected", and a
  # shade-any-six solution names a count rather than the cells.
  def state_for(question)
    solution = question.grading["solution"] || {}

    case question.widget_type
    when "multi_select" then { "selected" => solution["correct"] }
    when "grid_shade" then solution["count"] ? { "cells" => Array.new(solution["count"].to_i) { |i| "9,#{i}" } } : solution
    else solution
    end
  end

  # A sample rather than the lot: enough to catch a family whose answer does not
  # match its own question, without importing 10k rows.
  it "grades a sample of every file correct when given its own answer" do
    topics = ProblemSeeds.import_topics(topics_file)
    sample = files.flat_map { |path| YAML.safe_load_file(path).fetch("problems").each_slice(40).map(&:first) }

    stats = ProblemSeeds.import(sample, topics)
    stats[:skipped].should eq(0)

    Question.published.find_each do |question|
      raw = case question.answer_type
      when "exact_value" then { value: question.grading["expected"] }
      when "multiple_choice" then { selected_ids: question.correct_possible_answers.map(&:id) }
      when "interactive" then { state: state_for(question).to_json }
      end

      Grading.grade(question: question, raw: raw).correct.should be(true), question.body_text
    end
  end
end
